# Page settings

languageCode = "en-us"
title = "Joseph Ting CV"
theme = "hugo-orbit-theme"
# googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Curriculum vitae (CV) / resume of Joseph Ting"
    author = "Joseph Ting"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "John Doe"
        tagline = "Full Stack Web Developer"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        # [[params.contact.list]]
        # class = "email"
        # icon = "fa-envelope"
        # url = "mailto: yourname@email.com"
        # title = "john.doe@website.com"

        # [[params.contact.list]]
        # class = "phone"
        # icon = "fa-phone"
        # url = "tel:+1234567890"
        # title = "+1234567890"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//josephting.my"
        title = "josephting.my"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//www.linkedin.com/in/josephting/"
        title = "linkedin.com/in/josephting"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/josephting"
        title = "github.com/josephting"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/josephting"
        title = "@josephting"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Diploma in Computer Science & Statistics"
        college = "Tunku Abdul Rahman College"
        dates = "2008 - 2010"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Mandarin Chinese"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

        [[params.language.list]]
        language = "Japanese"
        level = "Professional"

        [[params.language.list]]
        language = "Malay"
        level = "Fluent"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Movies"

        [[params.interests.list]]
        interest = "PC Games"

        [[params.interests.list]]
        interest = "Piano"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "Majority consists of freelance experience where self-teaching while consuming online resources has been the norm since the dawn of contact with programming back in year 2005. Continue to check out interesting new technologies being released ever since and for years to come."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Web DevOps"
        dates = "2013 - 2016"
        company = "Freelance"
        details = "In charge of web hosting infrastructure designs, database designs, frontend (bootstrap + custom designs) & backend (**PHP**, **Laravel**, **Pusher**) development, deployment and general operation administration for a asynchronous realtime browser based gaming website."

        [[params.jobs.list]]
        position = "Web Developer"
        dates = "2010 - 2013"
        company = "Mo.Ad Media Sdn. Bhd."
        details = "Wordpress theme development including HTML conversions for several sites based off of designs provided by colleague in Photoshop. Also includes general cPanel management."

        [[params.jobs.list]]
        position = "Website Assistant"
        dates = "2009 - 2010"
        company = "Freelance"
        details = "Mainly in-charge of content updating as well as layout adjustments of WordPress sites. Also made landing pages for internet marketers."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "HTML5 & CSS"
        level = "97%"

        [[params.skills.list]]
        skill = "JavaScript"
        level = "88%"

        [[params.skills.list]]
        skill = "Git"
        level = "85%"

        [[params.skills.list]]
        skill = "PHP"
        level = "84%"

        [[params.skills.list]]
        skill = "Vue.js"
        level = "80%"

        [[params.skills.list]]
        skill = "Python"
        level = "77%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
